/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.electronicos.Forms;

import com.electronicos.models.Producto;
import dao.ProductoDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class cambioAgregar extends javax.swing.JPanel {
    private int option;
    private int id;
    /**
     * Creates new form Producto
     */
    public cambioAgregar(int option, int id) {
        this.option = option;
        this.id = id;
        initComponents();
        if(option == 1){
            this.btnCambiarAgregar.setText("Agregar");
            this.lblTitulo.setText("Bienvenido, Agrege un Producto para comenzar");
        } else{
            this.btnCambiarAgregar.setText("Actualizar");
            this.lblTitulo.setText("Bienvenido, Modifique un Producto para comenzar");
        }
    }
    
    public cambioAgregar(int option){
        this.option = option;
        initComponents();
        if(option == 1){
            this.btnCambiarAgregar.setText("Agregar");
            this.lblTitulo.setText("Bienvenido, Agrege un Producto para comenzar");
        } else{
            this.btnCambiarAgregar.setText("Actualizar");
            this.lblTitulo.setText("Bienvenido, Modifique un Producto para comenzar");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtFieldNombreProducto = new javax.swing.JTextField();
        lblNombreProduc = new javax.swing.JLabel();
        txtFieldMarcaProducto = new javax.swing.JTextField();
        lblIdMarca = new javax.swing.JLabel();
        txtFieldCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        lblPrecio = new javax.swing.JLabel();
        txtAreaPrecio = new javax.swing.JTextField();
        lblIdProveedor = new javax.swing.JLabel();
        txtAreaIdProveedor = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        txtAreaCategoria = new javax.swing.JTextField();
        btnCambiarAgregar = new javax.swing.JButton();

        lblTitulo.setText("Bienvenido a la pantalla de Agregar Productos");

        lblNombreProduc.setText("Nombre del Producto");

        lblIdMarca.setText("Id de la Marca del Producto");

        lblCantidad.setText("Cantidad");

        lblDescripcion.setText("Descripcion");

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescripcion);

        lblPrecio.setText("Precio");

        lblIdProveedor.setText("Id del Proveedor");

        txtAreaIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaIdProveedorActionPerformed(evt);
            }
        });

        lblCategoria.setText("Id Categoria");

        btnCambiarAgregar.setText("Agregar");
        btnCambiarAgregar.setActionCommand("");
        btnCambiarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCantidad)
                        .addComponent(txtFieldMarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdMarca)
                        .addComponent(txtFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescripcion)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrecio)
                        .addComponent(txtAreaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdProveedor)
                        .addComponent(txtAreaIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCategoria)
                        .addComponent(txtAreaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNombreProduc)
                        .addComponent(txtFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCambiarAgregar)
                        .addGap(307, 307, 307))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(lblNombreProduc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIdMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFieldMarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAreaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIdProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAreaIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAreaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCambiarAgregar)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAreaIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaIdProveedorActionPerformed

    private void btnCambiarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarAgregarActionPerformed
    boolean validData = false;


    boolean mostrarCuadro = true;

while (!validData && mostrarCuadro) {
    try {
        String nombre = this.txtFieldNombreProducto.getText();
        int idMarca = Integer.valueOf(this.txtFieldMarcaProducto.getText());
        int cantidad = Integer.valueOf(this.txtFieldCantidad.getText());
        String desc = this.txtAreaDescripcion.getText();
        int precio = Integer.valueOf(this.txtAreaPrecio.getText());
        int idProv = Integer.valueOf(this.txtAreaIdProveedor.getText());
        int categoria = Integer.valueOf(this.txtAreaCategoria.getText());
        Producto producto = new Producto(nombre, idMarca, cantidad, desc, precio, idProv, categoria);
        ProductoDao dao = new ProductoDao();
        switch (option) {
            case 1:
                dao.agregarProducto(producto);
                break;
            case 2:
                dao.actualizarProducto(this.id, producto);
        }
        validData = true;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese solo valores numéricos para los campos idMarca, cantidad, precio, idProv y categoria.", "Error de formato de número", JOptionPane.ERROR_MESSAGE);
        limpiarDatos();
        mostrarCuadro = false;
    }
}

limpiarDatos();
         
    }//GEN-LAST:event_btnCambiarAgregarActionPerformed
    
    
    private void limpiarDatos(){
        this.txtAreaCategoria.setText("");
        this.txtAreaDescripcion.setText("");
        this.txtAreaPrecio.setText("");
        this.txtAreaIdProveedor.setText("");
        this.txtAreaCategoria.setText("");
        this.txtFieldCantidad.setText("");
        this.txtFieldNombreProducto.setText("");
        this.txtFieldMarcaProducto.setText("");
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblIdMarca;
    private javax.swing.JLabel lblIdProveedor;
    private javax.swing.JLabel lblNombreProduc;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAreaCategoria;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtAreaIdProveedor;
    private javax.swing.JTextField txtAreaPrecio;
    private javax.swing.JTextField txtFieldCantidad;
    private javax.swing.JTextField txtFieldMarcaProducto;
    private javax.swing.JTextField txtFieldNombreProducto;
    // End of variables declaration//GEN-END:variables
}
